version: '3'

networks:
  default:

services:
  postgres:
    image: postgres:10
    container_name: postgres
    ports:
      - "5544:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    networks:
      - default

  email:
    image: email
    ports:
      - "15002:80"
    build:
      context: .
      dockerfile: ./EmailService/Dockerfile
    container_name: email-api
    environment:
      - APP_BUILD=v1.001
      - ASPNETCORE_ENVIRONMENT=Development
    restart: unless-stopped
    networks:
      - default
    logging:
      driver: "json-file"
      options:
        max-size: "3000m"
        max-file: "1"
    depends_on:
      - postgres

  message:
    image: message
    ports:
      - "15004:80"
    build:
      context: .
      dockerfile: ./MessageService/Dockerfile
    container_name: message-api
    environment:
      - APP_BUILD=v1.001
      - ASPNETCORE_ENVIRONMENT=Development
    restart: unless-stopped
    networks:
      - default
    logging:
      driver: "json-file"
      options:
        max-size: "3000m"
        max-file: "1"
    depends_on:
      - postgres

  notification:
    image: notification
    ports:
      - "15004:80"
    build:
      context: .
      dockerfile: ./NotificationService/Dockerfile
    container_name: notification-api
    environment:
      - APP_BUILD=v1.001
      - ASPNETCORE_ENVIRONMENT=Development
    restart: unless-stopped
    networks:
      - default
    logging:
      driver: "json-file"
      options:
        max-size: "3000m"
        max-file: "1"
    depends_on:
      - postgres

  rabbitmq: # login guest:guest
    image: masstransit/rabbitmq
    container_name: rabbitmq
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    networks:
      - default
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "25672:25672"
      - "15671:15671"
      - "15672:15672"

  redis-cache:
    image: redis/redis-stack-server:latest
    restart: always 
    networks:
      - default
    ports:
      - 6379:6379